# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  demo_build: ./build/demo_tasks.yml
  pages_demo: ./build/github_pages/demo_tasks.yml

tasks:
  rear-demo:
    desc: Demo files
    cmds:
      - task: demo_build:rear-demo-content
      - task: demo_build:rear-demo-presentation
      - task: demo_build:rear-demo-behavior
      - echo "Demo ready"
  pages-demo:
    desc: Copy demo files into pages host directory
    deps: [rear-demo]
    cmds:
      - cp distribution/demo/demo.html docs/index.html
      - cp distribution/demo/main.css docs/main.css
      - cp distribution/demo/main.js docs/main.js
      - echo "Pages host directory for demo is ready"
  sweep-demo:
    desc: Remove generated files
    cmds:
      - task: demo_build:sweep-demo-content
      - task: demo_build:sweep-demo-presentation
      - task: demo_build:sweep-demo-behavior
      - echo "Demo gone"
  sweep-pages-demo:
    desc: Clear out pages host directory
    cmds:
      - task: pages_demo:sweep-pages-demo-content
      - task: pages_demo:sweep-pages-demo-presentation
      - task: pages_demo:sweep-pages-demo-behavior
      - echo "Pages host directory cleared"
