# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json

# Running commands looks like:
# task TARGET:OBJECTIVE:action-AREA 
# 
# (see build/README.md)
# 

version: '3'

includes:
  octocat: ./Build/octocat/_tasks.yml

tasks:
  check_env:
    cmds:
      - echo $PROJECT_DIR
      - echo $BEHAVIOR_DIR
      - echo "Unix timestamp {{now | unixEpoch}}"

  # Top level aliases for convenience

  rear-octocat-v0-fhost:
    aliases: [rear-file]
    cmds:
      - task: octocat:v0:rear-fhost

  rear-octocat-v0-lhost:
    aliases: [rear-local]
    cmds:
      - task: octocat:v0:rear-lhost

  rear-octocat-v0-prod:
    aliases: [rear-prod]
    cmds:
      - task: octocat:v0:rear-prod

  sweep-octocat-v0-fhost:
    cmds:
      - task: octocat:v0:sweep-fhost

  sweep-octocat-v0-lhost:
    aliases: [sweep-local]
    cmds:
      - task: octocat:v0:sweep-lhost

  sweep-octocat-v0-prod:
    aliases: [sweep-prod]
    cmds:
      - task: octocat:v0:sweep-prod