# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  pages-demo:
    desc: Copy demo files into pages host directory
    deps: [rear-demo]
    cmds:
      - cp distribution/demo/demo.html docs/index.html
      - cp distribution/demo/main.css docs/main.css
      - cp distribution/demo/main.js docs/main.js
  rear-demo:
    desc: Demo files
    cmds:
      - task: rear-demo-content
      - task: rear-demo-presentation
      - task: rear-demo-behavior
      - echo "Demo ready"
  sweep-demo:
    desc: Remove generated files
    cmds:
      - rm -f distribution/demo/demo.html distribution/demo/main.css distribution/demo/main.{js,mjs}
      - echo "Demo gone"
  sweep-pages-demo:
    desc: Clear out pages host directory
    cmds:
      - rm docs/index.html docs/main.css docs/main.js

  rear-demo-presentation:
    internal: true
    desc: Stlus to CSS
    cmds:
      - pnpm stylus source/presentation/demo.styl -o distribution/demo/main.css
  rear-demo-content:
    internal: true
    desc: Pug to HTML
    cmds:
      - pnpm pug source/content/demo.pug -o distribution/demo/
  rear-demo-behavior:
    internal: true
    desc: JS
    cmds:
      - cp source/behavior/demo.js distribution/demo/main.js
