# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json

# Running commands looks like:
# task TARGET:OBJECTIVE:action-AREA 
# 
# (see build/README.md)
# 

version: '3'

vars:
  PRESENTATION_REL:
    sh: realpath --relative-to="{{.PROJECT_DIR}}" "{{.PRESENTATION_DIR}}"
  DEV_REL:
    sh: realpath --relative-to="{{.PROJECT_DIR}}" "{{.DEV_DIR}}"

includes:
  soi: ./build/_tasks.yml
  octocat: ./build/octocat/_tasks.yml
  assess: ./test/_tasks.yml

tasks:
  check_env:
    cmds:
      - echo $PROJECT_DIR
      - echo $BEHAVIOR_DIR
      - echo "Unix timestamp {{now | unixEpoch}}"
      - echo $VERSION_NUM

  nitJS:
    cmds:
      - pnpm eslint -c {{.PROJECT_DIR}}/eslint.config.mjs {{.CLI_ARGS}}
