# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  demo_build: ./build/demo_tasks.yml
  pages_demo: ./build/github_pages/demo_tasks.yml

tasks:
  check_env:
    cmds:
      - echo $PROJECT_DIR
      - echo $BEHAVIOR_DIR
  rear-demo:
    desc: Demo files
    cmds:
      - task: demo_build:rear-content
      - task: demo_build:rear-presentation
      - task: demo_build:rear-behavior
      - task: demo_build:put-vendor
      - echo "Demo ready"
  pages-demo:
    desc: Copy demo files into pages host directory
    deps: [rear-demo]
    cmds:
      - cp {{.DIST_DIR}}/demo/demo.html {{.PAGES_HOST_DIR}}/index.html
      - cp {{.DIST_DIR}}/demo/reset.css {{.PAGES_HOST_DIR}}/reset.css
      - cp {{.DIST_DIR}}/demo/main.css {{.PAGES_HOST_DIR}}/main.css
      - cp {{.DIST_DIR}}/demo/main.js {{.PAGES_HOST_DIR}}/main.js
      - cp {{.DIST_DIR}}/demo/html2canvas.js {{.PAGES_HOST_DIR}}/html2canvas.js
      - cp {{.DIST_DIR}}/demo/chance.js {{.PAGES_HOST_DIR}}/chance.js
      - echo "Pages host directory for demo is ready"
  sweep-demo:
    desc: Remove generated files
    cmds:
      - task: demo_build:sweep-content
      - task: demo_build:sweep-presentation
      - task: demo_build:sweep-behavior
      - echo "Demo gone"
  sweep-pages-demo:
    desc: Clear out pages host directory
    cmds:
      - task: pages_demo:sweep-content
      - task: pages_demo:sweep-presentation
      - task: pages_demo:sweep-behavior
      - echo "Pages host directory cleared"
