# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  octocat_v0_fhost: ./build/octocat/v0/fhost_tasks.yml
  octocat_v0_prod: ./build/octocat/v0/prod_tasks.yml

tasks:
  check_env:
    cmds:
      - echo $PROJECT_DIR
      - echo $BEHAVIOR_DIR
  rear-octocat-v0-fhost:
    desc: Build demo files
    cmds:
      - task: octocat_v0_fhost:rear-content
      - task: octocat_v0_fhost:rear-presentation
      - task: octocat_v0_fhost:rear-behavior
      - task: octocat_v0_fhost:put-vendor
      - task: octocat_v0_fhost:put-meta
      - echo "Demo file-host ready"
  rear-octocat-v0-prod:
    desc: Build demo files
    cmds:
      - task: octocat_v0_prod:rear-content
      - task: octocat_v0_prod:rear-presentation
      - task: octocat_v0_prod:rear-behavior
      - task: octocat_v0_prod:put-vendor
      - task: octocat_v0_prod:put-meta
      - echo "ocotcat host directory for demo is ready"
  sweep-octocat-v0-fhost:
    desc: Remove generated files
    cmds:
      - task: octocat_v0_fhost:sweep-content
      - task: octocat_v0_fhost:sweep-presentation
      - task: octocat_v0_fhost:sweep-behavior
      - task: octocat_v0_fhost:sweep-vendor
      - task: octocat_v0_fhost:sweep-meta
      - echo "Demo file-host cleared"
  sweep-octocat-v0-prod:
    desc: Remove generated files
    cmds:
      - task: octocat_v0_prod:sweep-content
      - task: octocat_v0_prod:sweep-presentation
      - task: octocat_v0_prod:sweep-behavior
      - task: octocat_v0_prod:sweep-vendor
      - task: octocat_v0_prod:sweep-meta
      - echo "octocat host directory cleared"
