# For a guide to configuration, visit https://qlty.sh/d/config
# Or for a full reference, visit https://qlty.sh/d/qlty-toml
config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "demo.main.js",
  "trythis.example.js",
  "**/*.d.ts",
  "**/.brwud/**",
  "**/assets/**",
  "**/build/**",
  "**/dist/**",
  "**/coverage/**",
  "**/source/content/**",
  "**/source/presentation/**",
  "**/distribution/**",
  "**/node_modules/**",
  "**/vendor/**"
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/stories/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*"
]

[smells]
mode = "comment"

[[source]]
name = "default"
default = true
repository = "https://github.com/bharrisaplus/pcs_web.git"


[[plugin]]
name = "actionlint"

[[plugin]]
name = "editorconfig-checker"
mode = "comment"

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "zizmor"

[[plugin]]
name = "shellcheck"
config_files = [".shellcheckrc"]

[[plugin]]
name = "stylelint"
package_file = "package.json"
package_filters = ["stylelint"]
config_files = ["stylelint.config.mjs"]

[[plugin]]
name = "oxc"
config_files = [".oxlintrc.json"]
